### ISSUE TITLE
Playground tracking issue / feature requests

### ISSUE THREAD

**Issue by jakobhellermann** [jakobhellermann/bevy_mod_debugdump#15]
https://jakobhellermann.github.io/bevy_mod_debugdump/?schedule=Main&include=bevy_render,bevy_pbr
Code at https://github.com/jakobhellermann/bevy_mod_debugdump/tree/pages

- [x] share link and load options from URL params
- [x] select schedule, includes and excludes
- [ ] filter by copmonent access
- [ ] make zoom work

**Comment by hymm** [comment]
would it be possible to filter by SystemParam names?

**Comment by hymm** [comment]
> It would be possible to filter by component/resource access, if you mean that

yeah.
